name:                legendary-bench
version:             0.1.0.0
github:              "githubuser/legendary-bench"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/legendary-bench#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
    - servant-server
    - stm
    - transformers
    - text
    - unordered-containers
    - containers
    - hashable
    - mtl
    - lens
    - random
    - wai-cors
    - wai-extra
    - s-cargot

executables:
  legendary-bench-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - legendary-bench
    - servant-server
    - wai
    - warp
  benchmarks-exe:
    main: Main.hs
    source-dirs: benchmark
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - legendary-bench
    - criterion
    - random-shuffle
    - random
    - containers
    - deepseq

tests:
  legendary-bench-test:
    main:                Driver.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - legendary-bench
    - aeson
    - tasty
    - tasty-discover
    - tasty-hunit
    - tasty-quickcheck
    - random
    - random-shuffle
    - lens
    - containers
    - unordered-containers
    - text
    - hashable
    - parsec
    - s-cargot
    - mtl
